services:
  mysql:
    image: mysql:8.0
    container_name: lumi
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumi
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - lumi_data:/var/lib/mysql

volumes:
  lumi_data: